"""Initial_tables

Revision ID: 6cc0afd21697
Revises: 
Create Date: 2026-03-01 20:56:02.003556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc0afd21697'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'PROCESSING', 'DOWNLOADING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('style', sa.Enum('JAPANESE_ANIME', 'REALISTIC', 'CLAY_3D', 'CYBERPUNK', name='artstyle'), nullable=False),
    sa.Column('aspect_ratio', sa.Enum('SQUARE', 'PORTRAIT', 'LANDSCAPE', 'STORY', name='aspectratio'), nullable=False),
    sa.Column('reference_image_url', sa.String(), nullable=True),
    sa.Column('result_url', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('external_task_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation_tasks')
    # ### end Alembic commands ###
